'use client';

import { RotateCcw, Smile, Activity, Brain, ClipboardList } from 'lucide-react';
import type { Report } from '@/lib/types';

/** Pulls an "X / 10" or "X out of 10" score out of the recall clarity string. */
function extractScore(value: string): number | null {
  const match = value.match(/(\d{1,2})\s*(?:\/\s*10|out of\s*10)/i);
  if (match) {
    const n = parseInt(match[1], 10);
    if (n >= 0 && n <= 10) return n;
  }
  return null;
}

interface ReportViewProps {
  report: Report | null;
  onReset: () => void;
}

export default function ReportView({ report, onReset }: ReportViewProps) {
  if (!report) {
    return (
      <div className="mx-auto max-w-2xl px-6 py-16 text-center text-ink/70">
        No report data was found.
      </div>
    );
  }

  const score = extractScore(report.recallClarity);

  const secondaryCards = [
    {
      icon: <Smile className="h-7 w-7 text-sage-600" aria-hidden="true" />,
      title: 'Sentiment',
      body: report.sentiment,
    },
    {
      icon: <Activity className="h-7 w-7 text-paleblue-700" aria-hidden="true" />,
      title: 'Engagement',
      body: report.engagementMetrics,
    },
  ];

  return (
    <div className="mx-auto w-full max-w-3xl px-5 py-10">
      <div className="mb-8 flex flex-col items-center text-center">
        <ClipboardList className="mb-3 h-10 w-10 text-sage-600" aria-hidden="true" />
        <h1 className="text-4xl font-semibold text-ink">Session Summary</h1>
        <p className="mt-2 text-lg text-ink/60">A gentle overview prepared for the care team.</p>
      </div>

      {/* Recall clarity (with optional score bar) */}
      <section className="mb-5 rounded-3xl border border-paleblue-200 bg-white p-6 shadow-soft">
        <div className="mb-3 flex items-center gap-3">
          <Brain className="h-7 w-7 text-paleblue-700" aria-hidden="true" />
          <h2 className="text-2xl font-semibold text-ink">Recall Clarity</h2>
          {score !== null ? (
            <span className="ml-auto rounded-full bg-sage-100 px-4 py-1 text-lg font-semibold text-sage-700">
              {score}/10
            </span>
          ) : null}
        </div>

        {score !== null ? (
          <div
            className="mb-4 h-4 w-full overflow-hidden rounded-full bg-paleblue-100"
            role="progressbar"
            aria-valuenow={score}
            aria-valuemin={0}
            aria-valuemax={10}
          >
            <div
              className="h-full rounded-full bg-sage-600 transition-all"
              style={{ width: `${score * 10}%` }}
            />
          </div>
        ) : null}

        <p className="text-lg leading-relaxed text-ink/80">{report.recallClarity}</p>
      </section>

      {/* Sentiment + Engagement */}
      <div className="mb-5 grid gap-5 sm:grid-cols-2">
        {secondaryCards.map((c) => (
          <section
            key={c.title}
            className="rounded-3xl border border-paleblue-200 bg-white p-6 shadow-soft"
          >
            <div className="mb-3 flex items-center gap-3">
              {c.icon}
              <h2 className="text-2xl font-semibold text-ink">{c.title}</h2>
            </div>
            <p className="text-lg leading-relaxed text-ink/80">{c.body}</p>
          </section>
        ))}
      </div>

      {/* Clinical summary */}
      <section className="mb-8 rounded-3xl border border-sage-500 bg-sage-100 p-6 shadow-soft">
        <div className="mb-3 flex items-center gap-3">
          <ClipboardList className="h-7 w-7 text-sage-700" aria-hidden="true" />
          <h2 className="text-2xl font-semibold text-ink">Clinical Summary</h2>
        </div>
        <p className="text-lg leading-relaxed text-ink">{report.clinicalSummary}</p>
      </section>

      <button
        type="button"
        onClick={onReset}
        className="flex w-full items-center justify-center gap-3 rounded-2xl bg-sage-600 px-6 py-4 text-xl font-semibold text-white shadow-soft transition hover:bg-sage-700"
      >
        <RotateCcw className="h-6 w-6" aria-hidden="true" />
        Start New Session
      </button>

      <p className="mt-4 text-center text-sm text-ink/50">
        This summary is generated by an AI and is not a medical diagnosis. Please review it
        with a qualified clinician.
      </p>
    </div>
  );
}
